name: Issue article helper
description: Check article grammar with chatgpt
inputs:
  delimiters: # id of input
    description: gray matter delimiters
    required: false
  ownerOnly:
    description: only repo owner can trigger this action
    required: false
    default: true
  removeCodeblocks:
    description: remove code blocks before send to ChatGPT
    required: false
    default: false
runs:
  using: node16
  main: dist/index.js
