name: Issue article helper
description: Check article grammar with chatgpt
inputs:
  delimiters: # id of input
    description: gray matter delimiters
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
